dbtstudio_getting_started:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: >-
        C:\Users\Edon\rosetta-dbt-studio-projects\dbtstudio_getting_started\rosetta\university_sample.duckdb
      schema: main
      threads: 4
