openai_api_key: ${openai-api-key}
connections:
  - name: dbtstudio_getting_started
    databaseName: ${db-dbname-Test}
    schemaName: ${db-schema-Test}
    dbType: postgres
    url: >-
      jdbc:postgresql://${db-host-Test}:${db-port-Test}/${db-dbname-Test}?currentSchema=${db-schema-Test}
    userName: ${db-user-Test}
    password: ${db-password-Test}
